@api-URL = http://localhost:{{$dotenv PORT}}

POST {{api-URL}}/posts HTTP/1.1
Content-Type: application/json

{
    "titulo": "o morro dos ventos uivantes",
    "conteudo": "dchqgevjewvfhbvjhwbfvhkebrjvbebvjhbvjhbjhwvbjhbvgrbv",
    "Idautor": 4
}